### ISSUE TITLE
How to use KgCoOp in new dataset?

### ISSUE THREAD

**Issue by jianandeng023** [htyao89/KgCoOp#5]
Thanks for your valuable work!
I have a new data set, how do I implement the KgCoOp on the new data?

**Comment by htyao89** [comment]
> Thanks for your valuable work! I have a new data set, how do I implement the KgCoOp on the new data?

I am sorry that we use the standard dataset for training and evaluation, and we do not implement CoOp-based methods on the new data.

**Comment by jianandeng023** [comment]
Maybe I can do a new dataset validation following your Settings for these standard datasets?
